In [1]:
import pandas as pd

C:\Users\simon\AppData\Local\Temp\ipykernel_1184\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv("data/ballot_1.csv")
df

       party   votes  is_ind region
0    party_1  186141   False     ec
1    party_2  187891   False     ec
2    party_3   93239   False     ec
3    party_4   44912   False     ec
4    party_5  -30515   False     ec
..       ...     ...     ...    ...
463    ind_2  221439    True     wc
464    ind_3 -786343    True     wc
465    ind_4  280845    True     wc
466    ind_5  273780    True     wc
467    ind_6  398219    True     wc

[468 rows x 4 columns]